name: Twice-a-week Audit

on:
  schedule:
    - cron: '0 7 * * 2,4'
  workflow_dispatch:

jobs:
  scheduled-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: docker build -t flask-app-local .

      - name: Run Scheduled Tests inside Docker
        run: docker run --entrypoint "" flask-app-local pytest -v